name: Full CI

on:
  push:
    branches: [ "main" ]

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22   

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Run build
        run: npm run ng -- build --configuration production 
        working-directory: frontend

  backend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore packages
        run: dotnet restore
        working-directory: backend

      - name: Build project
        run: dotnet build --configuration Release
        working-directory: backend
